### ISSUE TITLE
awsdownload error

### ISSUE THREAD

**Issue by rhalherrero** [kraftek/awsdownload#10]
I  don't know how to delete the issue!!
Sorry!

**Comment by kraftek** [comment]
No worries.
Have you find the cause? I've run with your arguments and it started to download 27 products

**Comment by rhalherrero** [comment]
I didn't build and package the project before
Now I get an error when building the because I have to install JDK beforehand. Is this mandatory?
I don´t really work with Java, and I only need this to download sentinel data.

**Comment by kraftek** [comment]
For building you'd need a JDK since the JRE doesn't include the Java compiler.
You can download the latest release binaries instead, if you'd like only to use the tool to download data.
