### ISSUE TITLE
S2MSI2A product type

### ISSUE THREAD

**Issue by tomas4** [kraftek/awsdownload#13]
Latest level-2 products are no longer provisional and consequently new level-2 product type is S2MSI2A, not S2MSI2Ap (but the older scenes are still of type S2MSI2Ap). New product type should be added for the parameter -s2t (but the old preserved). This relates to search and downloads from SCIHUB, I did not test with AWS.
Regards,
Tomas

**Comment by kraftek** [comment]
New product type added.
