### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException 	at ro.cs.s2.S2ProductDownloader.main(S2ProductDownloader.java:336)

### ISSUE THREAD

**Issue by BayAludra** [kraftek/awsdownload#3]
I followed the installation instruction from the Readme on Windows Server 2012 R2. Java and mvn should be installed properly (I have jre and jdk 1.8)

When running the example command from the Readme I am getting the following NullPointerException: 

Command: 

`java -jar S2ProductDownloader-1.0.jar --out D:\Products --tiles 34TFQ 35TNL --products S2A_OPER_PRD_MSIL1C_PDMC_20160103T183955_R064_V20160103T085753_20160103T085753 --store AWS
`

`2016-08-03 09:03:43    [INFO]      Executing with the following arguments:
2016-08-03 09:03:43 [INFO]      o=D:\Products
2016-08-03 09:03:43 [INFO]      t=34TFQ
2016-08-03 09:03:43 [INFO]      p=S2A_OPER_PRD_MSIL1C_PDMC_20160103T183955_R064_V20160103T085753_20160103T085753
2016-08-03 09:03:43 [INFO]      s=AWS
Exception in thread "main" java.lang.NullPointerException
    at ro.cs.s2.S2ProductDownloader.main(S2ProductDownloader.java:336)
`

Any ideas? 

May be it has to do with the installation because I had to copy the .jar file and lib folder manuelly. During the assembly I got the warning: 

`[WARNING] Assembly file: D:\awsdownload\target\S2ProductDownloader-1.0-bin is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.608 s
[INFO] Finished at: 2016-08-03T09:08:50+00:00
[INFO] Final Memory: 20M/1182M
[INFO] ------------------------------------------------------------------------`

**Comment by kraftek** [comment]
This is because you have not supplied your user name and password for SciHub.
I have made them mandatory, you can take the changes from GitHub.

**Comment by BayAludra** [comment]
Thanks a lot, that indeed solved the issue.
