### ISSUE TITLE
Query using Scientific Data Hub returns 14 results but only the first 10 are downloaded

### ISSUE THREAD

**Issue by BayAludra** [kraftek/awsdownload#4]
If I am using the Scientific Data Hub for querying for possible tiles I am not getting the correct number of tiles. 

With the following link one receives 14 results in total but only the results 0-9 are shown: 

https://scihub.copernicus.eu/apihub/search?rows=10&q=platformName%3ASentinel-2%20AND%20beginPosition%3A[NOW-171DAY%20TO%20NOW]%20AND%20relativeOrbitNumber%3A93%20AND%20footprint%3A%22Intersects%28POLYGON%28%2822.2506169248%2044.1352507247%2C23.6676210768%2044.1352507247%2C23.6676210768%2045.1467528551%2C22.2506169248%2045.1467528551%2C22.2506169248%2044.1352507247%29%29%29%22

Therefore, the tool is downloading only 10 tiles instead of the 14 existing results. When using AWS to search for available tiles everything works fine.

**Comment by kraftek** [comment]
Hello.

Please review all the supported command line arguments. There is an argument (-l or --limit) that controls how many results are returned by SciHub. The default is 10.

----- Reply message -----
