### ISSUE TITLE
Error attempting to process download products with sen2cor 2.3.1

### ISSUE THREAD

**Issue by jdesbonnet** [kraftek/awsdownload#8]
I'm attempting to write a script to generate NDVI images efficiently. This project looks like a perfect starting point, but when I try to apply atmospheric correction with sen2cor (v 2.3.1) I get an error:

```
Traceback (most recent call last):
  File "/home/joe/anaconda2/bin/L2A_Process", line 11, in <module>
    load_entry_point('sen2cor==2.3.1', 'console_scripts', 'L2A_Process')()
  File "/home/joe/anaconda2/lib/python2.7/site-packages/sen2cor-2.3.1-py2.7.egg/sen2cor/L2A_Process.py", line 169, in main
    config.setSchemes()
  File "/home/joe/anaconda2/lib/python2.7/site-packages/sen2cor-2.3.1-py2.7.egg/sen2cor/L2A_Config.py", line 3072, in setSchemes
    self.logger.fatal('wrong identifier for xml structure: ' + product)
AttributeError: 'NoneType' object has no attribute 'fatal'
```

The command line used to download is:

```
java -jar ProductDownload.jar --sensor S2 --bands B04 B08 --out ./out3 --tiles 34TFQ --startdate 2017-01-01 --aws --store AWS --cloudpercentage 20 --limit 70 
```

This appears to run correctly and generates directories such as S2A_MSIL1C_20170102T093402_N0204_R136_T34TFQ_20170102T093400.SAFE

I've verified that my sen2cor installation works with full sized products downloaded from directly SciHub.

I'm running the latest from master (commit 4202d94966317d284b6bb4e7d881b09810b8dd48).

**Comment by kraftek** [comment]
I'm afraid that Sen2Cor works only with full sized products.
You can post a request on the [S2TBX Forum](http://forum.step.esa.int/c/s2tbx) for Sen2Cor to support incomplete products in a future version.

**Comment by jdesbonnet** [comment]
Thanks for the quick reply. Actually the above error message was due to a reboot since my sen2cor test with full sized product (some init environment vars were missing). But after fixing the config it still didn't work with a different set of error messages... in line with what you say about it not working with full sized products.
