### ISSUE TITLE
howto skip already download files

### ISSUE THREAD

**Issue by rkanavath** [kraftek/awsdownload#9]
I had download some s2 tiles with awsdownloader and did some processing with other tools.
This is a part of complex workflow. Is there a way to skip re-download of files which are already in system?

maybe a check on md5sum or something else?

**Comment by kraftek** [comment]
Actually, unless you don't specifically set --mode=OVERWRITE, it will not download again the existing files, it will just check that their length matches the remote ones. If you would like to keep track on the downloaded products and not go through this check again, this is not yet implemented (it's on my list though).

**Comment by kraftek** [comment]
Or, if you already have a local product library, you can use the --mode=SYMLINK. I will update these days the wiki page with some examples.

**Comment by rkanavath** [comment]
Thanks. That is helpful.
